schema:
  path: openapi.json

generator:
  target_package: generated
  output: internal/generated

features:
  client: true
  server: false

naming:
  rules:
    - from: template_id
      to: TemplateID
    - from: request_id
      to: RequestID
    - from: machine_id
      to: MachineID
    - from: machine_count
      to: MachineCount
    - from: provider_api
      to: ProviderAPI

exclude_patterns:
  - path: /api/v1/requests/{request_id}/stream
    method: GET
