"""VMSS Handler - provisions VM Scale Sets via the Azure Compute SDK.

This is the primary handler for the Azure provider

It handles:
- Creating a VMSS with Flexible orchestration (default) or Uniform
- Listing instances in a VMSS for status checks
- Deleting VMSS instances and the scale set itself
"""

from __future__ import annotations

import uuid
from typing import Any, Optional

from domain.base.dependency_injection import injectable
from domain.request.aggregate import Request
from providers.azure.domain.template.azure_template_aggregate import AzureTemplate
from providers.azure.domain.template.value_objects import AzureProviderApi
from providers.azure.exceptions.azure_exceptions import (
    AzureValidationError,
    QuotaExceededError,
    TerminationError,
    VMSSCreationError,
    VMSSNotFoundError,
)
from providers.azure.infrastructure.error_utils import (
    canonical_azure_error_code,
    extract_azure_error_details,
)
from providers.azure.infrastructure.handlers.azure_handler import AzureHandler
from providers.azure.domain.template.value_objects import AzureVMSSOrchestrationMode


# Azure VM power-state → domain status mapping
_AZURE_STATE_MAP: dict[str, str] = {
    "PowerState/starting": "pending",
    "PowerState/running": "running",
    "PowerState/stopping": "stopping",
    "PowerState/stopped": "stopped",
    "PowerState/deallocating": "shutting-down",
    "PowerState/deallocated": "stopped",
    "ProvisioningState/creating": "pending",
    "ProvisioningState/succeeded": "running",
    "ProvisioningState/failed": "failed",
    "ProvisioningState/deleting": "shutting-down",
}


def _resolve_power_state(statuses: list[Any]) -> str:
    """Extract the domain status from a list of Azure InstanceViewStatus objects."""
    for status in statuses:
        code = status.code if hasattr(status, "code") else str(status.get("code", ""))
        if code.startswith("PowerState/"):
            return _AZURE_STATE_MAP.get(code, "unknown")
    # Fallback to provisioning state
    for status in statuses:
        code = status.code if hasattr(status, "code") else str(status.get("code", ""))
        if code.startswith("ProvisioningState/"):
            return _AZURE_STATE_MAP.get(code, "unknown")
    return "unknown"


def _status_attr(status: Any, attr: str, default: Any = None) -> Any:
    """Read Azure status attributes from SDK objects or dict-like test doubles."""
    if hasattr(status, attr):
        return getattr(status, attr)
    if isinstance(status, dict):
        return status.get(attr, default)
    return default


@injectable
class VMSSHandler(AzureHandler):
    """Handler that creates and manages VMSS resources.

    ``provider_api = "VMSS"`` or ``"VMSSUniform"``
    """

    # ------------------------------------------------------------------
    # acquire_hosts
    # ------------------------------------------------------------------

    def acquire_hosts(
        self, request: Request, template: AzureTemplate
    ) -> dict[str, Any]:
        """Create a VMSS and return the result.

        The VMSS is created using the ARM payload generated by
        ``AzureTemplate.to_azure_api_format()``. The create LRO is submitted
        and the VMSS name is returned immediately; instance discovery happens
        later via status checks.
        """
        vmss_name = template.vmss_name or f"vmss-{template.template_id}-{uuid.uuid4().hex[:8]}"
        resource_group = template.resource_group
        location = template.location

        self._logger.info(
            "Creating VMSS '%s' in resource group '%s' (location=%s, capacity=%d)",
            vmss_name,
            resource_group,
            location,
            request.requested_count,
        )

        try:
            # Resolve subnet_id if network_config is missing
            if not template.network_config:
                subnet_id = None
                if template.subnet_ids:
                    candidate = template.subnet_ids[0]
                    if candidate and candidate != "default-subnet":
                        subnet_id = candidate

                if subnet_id:
                    # Auto-create network_config from subnet_id
                    from providers.azure.domain.template.value_objects import (
                        AzureNetworkConfig,
                    )

                    template.network_config = AzureNetworkConfig(subnet_id=subnet_id)
                    self._logger.debug("Auto-created network_config from subnet_id: %s", subnet_id)
                else:
                    raise ValueError(
                        "No subnet specified. Add 'subnet_id' (full ARM resource ID) "
                        "to the template in subnet_ids or network_config, e.g.: "
                        "/subscriptions/<sub>/resourceGroups/<rg>/providers/"
                        "Microsoft.Network/virtualNetworks/<vnet>/subnets/<subnet>"
                    )

            arm_payload = template.to_azure_api_format()

            # Override capacity with the requested count
            arm_payload["sku"]["capacity"] = request.requested_count
            arm_payload["name"] = vmss_name

            compute = self.azure_client.compute_client

            # Resolve ssh_key_name → actual key data if needed. Must
            # happen after to_azure_api_format() has been called so
            # the resolved keys end up in the ARM payload's osProfile.
            if template.ssh_key_name and not template.ssh_public_keys:
                resolved_keys = template.resolve_ssh_keys(compute)
                # Patch the already-built ARM payload with the resolved keys
                vm_profile = arm_payload["properties"]["virtualMachineProfile"]
                vm_profile["osProfile"]["linuxConfiguration"] = {
                    "disablePasswordAuthentication": True,
                    "ssh": {
                        "publicKeys": [
                            {
                                "path": f"/home/{template.admin_username}/.ssh/authorized_keys",
                                "keyData": key,
                            }
                            for key in resolved_keys
                        ],
                    },
                }

            # Begin VMSS creation (long-running operation)
            poller = compute.virtual_machine_scale_sets.begin_create_or_update(
                resource_group_name=resource_group,
                vm_scale_set_name=vmss_name,
                parameters=arm_payload,
            )
            continuation_token = None
            if hasattr(poller, "continuation_token"):
                try:
                    continuation_token = poller.continuation_token()
                except Exception as exc:
                    self._logger.debug(
                        "Could not capture VMSS poller continuation token for '%s': %s",
                        vmss_name,
                        exc,
                    )

            self._logger.info(
                "Submitted VMSS create operation for '%s'; tracking will continue via status checks",
                vmss_name,
            )

            resource_ids = [vmss_name]
            return {
                "success": True,
                "resource_ids": resource_ids,
                "instances": [],
                "error_message": None,
                "provider_data": {
                    "vmss_name": vmss_name,
                    "resource_group": resource_group,
                    "location": location,
                    "provisioning_state": "creating",
                    "operation_status": "submitted",
                    "continuation_token": continuation_token,
                },
            }

        except Exception as exc:
            error_msg = f"Failed to create VMSS '{vmss_name}': {exc}"
            self._logger.error(error_msg)

            # Translate Azure SDK errors into domain exceptions where possible
            error_code = canonical_azure_error_code(exc)
            error_str = extract_azure_error_details(exc)["message"].lower()
            if error_code in {"QuotaExceeded", "OperationNotAllowed", "ResourceQuotaExceeded"} or (
                "quota" in error_str or "exceeded" in error_str
            ):
                raise QuotaExceededError(error_msg) from exc
            if error_code in {"InvalidRequest", "InvalidParameter", "BadRequest"} or (
                "validation" in error_str or "invalid" in error_str
            ):
                raise AzureValidationError(error_msg) from exc

            raise VMSSCreationError(
                message=error_msg,
                template_id=template.template_id,
                vmss_name=vmss_name,
            ) from exc

    # ------------------------------------------------------------------
    # check_hosts_status
    # ------------------------------------------------------------------

    def check_hosts_status(self, request: Request) -> list[dict[str, Any]]:
        """Return instance details for every VM in the VMSS(es)."""
        resource_ids: list[str] = getattr(request, "resource_ids", []) or []
        if not resource_ids:
            self._logger.warning("check_hosts_status called with no resource_ids")
            return []

        all_instances: list[dict[str, Any]] = []

        for vmss_name in resource_ids:
            # We need the resource group.  Convention: stored on request metadata
            # or fall back to the azure_client default.
            resource_group = (
                (request.metadata or {}).get("resource_group")
                or self.azure_client.resource_group
            )
            if not resource_group:
                self._logger.error(
                    "Cannot resolve resource_group for VMSS '%s'", vmss_name
                )
                continue

            try:
                instances = self._list_vmss_instances(
                    resource_group, vmss_name, include_instance_view=True
                )
                all_instances.extend(instances)
            except Exception as exc:
                self._logger.error(
                    "Failed to list instances for VMSS '%s': %s", vmss_name, exc
                )

        return all_instances

    # ------------------------------------------------------------------
    # release_hosts
    # ------------------------------------------------------------------

    def release_hosts(
        self,
        machine_ids: list[str],
        resource_id: str,
        context: Optional[dict[str, Any]] = None,
    ) -> None:
        """Delete specific VM instances from a VMSS, or the entire VMSS."""
        context = context or {}
        resource_group = (
            context.get("resource_group") or self.azure_client.resource_group
        )
        if not resource_group:
            raise TerminationError(
                "resource_group is required for release_hosts",
                resource_ids=machine_ids,
            )

        vmss_name = resource_id
        compute = self.azure_client.compute_client
        orchestration_mode = self._get_vmss_orchestration_mode(resource_group, vmss_name)

        delete_vmss = context.get("delete_vmss", False)

        if delete_vmss:
            if orchestration_mode == AzureVMSSOrchestrationMode.FLEXIBLE:
                attached_vms = self._list_vmss_instances(
                    resource_group, vmss_name, include_instance_view=False
                )
                for vm in attached_vms:
                    vm_name = vm.get("instance_id")
                    if not vm_name:
                        continue
                    poller = compute.virtual_machines.begin_delete(
                        resource_group_name=resource_group,
                        vm_name=vm_name,
                    )
                    poller.result()
            # Delete the entire VMSS
            self._logger.info(
                "Deleting entire VMSS '%s' in resource group '%s'",
                vmss_name,
                resource_group,
            )
            try:
                poller = compute.virtual_machine_scale_sets.begin_delete(
                    resource_group_name=resource_group,
                    vm_scale_set_name=vmss_name,
                )
                poller.result()
                self._logger.info("VMSS '%s' deleted successfully", vmss_name)
            except Exception as exc:
                raise TerminationError(
                    f"Failed to delete VMSS '{vmss_name}': {exc}",
                    resource_ids=[vmss_name],
                ) from exc
        elif machine_ids:
            # Delete specific instances from the VMSS
            self._logger.info(
                "Deleting %d instance(s) from VMSS '%s'",
                len(machine_ids),
                vmss_name,
                )
            try:
                if orchestration_mode == AzureVMSSOrchestrationMode.FLEXIBLE:
                    for vm_name in machine_ids:
                        poller = compute.virtual_machines.begin_delete(
                            resource_group_name=resource_group,
                            vm_name=str(vm_name),
                        )
                        poller.result()
                    self._logger.info(
                        "Deleted %d flexible VMSS instance(s) from '%s'",
                        len(machine_ids),
                        vmss_name,
                    )
                else:
                    resolved_instance_ids = self._resolve_vmss_instance_ids(
                        resource_group=resource_group,
                        vmss_name=vmss_name,
                        machine_ids=machine_ids,
                    )
                    poller = compute.virtual_machine_scale_sets.begin_delete_instances(
                        resource_group_name=resource_group,
                        vm_scale_set_name=vmss_name,
                        vm_instance_i_ds={"instance_ids": resolved_instance_ids},
                    )
                    poller.result()
                    self._logger.info(
                        "Deleted %d instance(s) from VMSS '%s'",
                        len(resolved_instance_ids),
                        vmss_name,
                    )
            except Exception as exc:
                raise TerminationError(
                    f"Failed to delete instances from VMSS '{vmss_name}': {exc}",
                    resource_ids=machine_ids,
                ) from exc

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _resolve_vmss_instance_ids(
        self,
        resource_group: str,
        vmss_name: str,
        machine_ids: list[str],
    ) -> list[str]:
        """Resolve mixed IDs (vm_id/vm_name/instance_id) to VMSS instance IDs."""
        if not machine_ids:
            return []

        compute = self.azure_client.compute_client
        resolved: list[str] = []

        try:
            vms = compute.virtual_machine_scale_set_vms.list(
                resource_group_name=resource_group,
                virtual_machine_scale_set_name=vmss_name,
            )
            lookup: dict[str, str] = {}
            for vm in vms:
                vmss_instance_id = str(getattr(vm, "instance_id", "") or "")
                if not vmss_instance_id:
                    continue
                lookup[vmss_instance_id] = vmss_instance_id

                vm_id = getattr(vm, "vm_id", None)
                if vm_id:
                    lookup[str(vm_id)] = vmss_instance_id

                vm_name = getattr(vm, "name", None)
                if vm_name:
                    lookup[str(vm_name)] = vmss_instance_id

            for machine_id in machine_ids:
                machine_id_str = str(machine_id)
                resolved.append(lookup.get(machine_id_str, machine_id_str))

            if resolved != [str(mid) for mid in machine_ids]:
                self._logger.debug(
                    "Resolved VMSS machine IDs for '%s': %s -> %s",
                    vmss_name,
                    machine_ids,
                    resolved,
                )
            return resolved
        except Exception as exc:
            self._logger.warning(
                "Failed to resolve VMSS instance IDs for '%s', using provided IDs: %s",
                vmss_name,
                exc,
            )
            return [str(mid) for mid in machine_ids]

    def _list_vmss_instances(
        self,
        resource_group: str,
        vmss_name: str,
        include_instance_view: bool = False,
    ) -> list[dict[str, Any]]:
        """Return a list of normalised instance dicts for a VMSS."""
        compute = self.azure_client.compute_client
        orchestration_mode = self._get_vmss_orchestration_mode(resource_group, vmss_name)

        if orchestration_mode == AzureVMSSOrchestrationMode.FLEXIBLE:
            return self._list_flexible_vmss_instances(
                resource_group=resource_group,
                vmss_name=vmss_name,
                include_instance_view=include_instance_view,
            )

        try:
            expand = "instanceView" if include_instance_view else None
            vms = compute.virtual_machine_scale_set_vms.list(
                resource_group_name=resource_group,
                virtual_machine_scale_set_name=vmss_name,
                expand=expand,
            )
        except Exception as exc:
            raise VMSSNotFoundError(
                f"Could not list VMs in VMSS '{vmss_name}': {exc}",
                vmss_name=vmss_name,
            ) from exc

        instances: list[dict[str, Any]] = []
        for vm in vms:
            instance_data = self._normalise_vm(vm, vmss_name, resource_group)
            instances.append(instance_data)
        return instances

    def get_vmss_resource_errors(
        self,
        resource_group: str,
        vmss_name: str,
    ) -> list[dict[str, Any]]:
        """Return VMSS-level provisioning errors even when no instances are visible yet."""
        compute = self.azure_client.compute_client
        try:
            vmss = compute.virtual_machine_scale_sets.get(
                resource_group_name=resource_group,
                vm_scale_set_name=vmss_name,
            )
        except Exception:
            return []

        errors: list[dict[str, Any]] = []
        provisioning_state = str(getattr(vmss, "provisioning_state", "") or "")
        statuses = getattr(vmss, "statuses", None) or []

        errors.extend(
            self._extract_vm_errors(
                statuses,
                instance_id=vmss_name,
                vmss_name=vmss_name,
            )
        )

        if provisioning_state.lower() == "failed" and not errors:
            errors.append({
                "error_code": "ProvisioningStateFailed",
                "error_message": f"VMSS '{vmss_name}' provisioning failed",
                "instance_id": vmss_name,
                "resource_id": vmss_name,
                "status_code": "ProvisioningState/failed",
                "status_level": "Error",
            })

        return errors

    def _get_vmss_orchestration_mode(
        self,
        resource_group: str,
        vmss_name: str,
    ) -> AzureVMSSOrchestrationMode:
        compute = self.azure_client.compute_client
        vmss = compute.virtual_machine_scale_sets.get(
            resource_group_name=resource_group,
            vm_scale_set_name=vmss_name,
        )
        raw_mode = getattr(vmss, "orchestration_mode", None) or "Flexible"
        return AzureVMSSOrchestrationMode(str(raw_mode))

    def _list_flexible_vmss_instances(
        self,
        resource_group: str,
        vmss_name: str,
        include_instance_view: bool = False,
    ) -> list[dict[str, Any]]:
        compute = self.azure_client.compute_client

        try:
            vms = list(compute.virtual_machines.list(resource_group_name=resource_group))
        except Exception as exc:
            raise VMSSNotFoundError(
                f"Could not list flexible VMs for VMSS '{vmss_name}': {exc}",
                vmss_name=vmss_name,
            ) from exc

        instances: list[dict[str, Any]] = []
        vmss_arm_suffix = f"/virtualMachineScaleSets/{vmss_name}"

        for vm in vms:
            vmss_ref = getattr(vm, "virtual_machine_scale_set", None)
            vmss_ref_id = getattr(vmss_ref, "id", None) if vmss_ref else None
            if vmss_ref_id:
                if not str(vmss_ref_id).endswith(vmss_arm_suffix):
                    continue
            else:
                vm_name = getattr(vm, "name", "") or ""
                if not vm_name.startswith(f"{vmss_name}_"):
                    continue

            if include_instance_view:
                try:
                    vm = compute.virtual_machines.get(
                        resource_group_name=resource_group,
                        vm_name=getattr(vm, "name"),
                        expand="instanceView",
                    )
                except Exception as exc:
                    self._logger.warning(
                        "Failed to fetch instance view for flexible VMSS VM '%s': %s",
                        getattr(vm, "name", "unknown"),
                        exc,
                    )

            instances.append(self._normalise_vm(vm, vmss_name, resource_group))

        return instances

    def _normalise_vm(
        self, vm: Any, vmss_name: str, resource_group: str
    ) -> dict[str, Any]:
        """Convert an Azure SDK VirtualMachineScaleSetVM to a normalised dict."""
        instance_id = getattr(vm, "instance_id", None) or getattr(vm, "name", "")
        vm_id = getattr(vm, "vm_id", instance_id)

        # Extract status
        status = "unknown"
        instance_view = getattr(vm, "instance_view", None)
        if instance_view and hasattr(instance_view, "statuses"):
            status = _resolve_power_state(instance_view.statuses)
            fleet_errors = self._extract_vm_errors(
                instance_view.statuses,
                instance_id=str(instance_id),
                vmss_name=vmss_name,
            )
        else:
            fleet_errors = []

        # Network IPs
        private_ip = None
        public_ip = None
        subnet_id = None
        nic_configs = None
        net_profile = getattr(vm, "network_profile", None)
        if net_profile:
            nic_configs = getattr(net_profile, "network_interfaces", None)
        if nic_configs:
            for nic in nic_configs:
                nic_id = getattr(nic, "id", None)
                if nic_id:
                    # We store the NIC ARM id; resolving actual IPs would
                    # require an extra network call.  Most callers use the
                    # compute instance_view or the NIC reference.
                    pass

        # Hardware profile → instance type
        hw = getattr(vm, "hardware_profile", None)
        instance_type = getattr(hw, "vm_size", None) if hw else None
        # Ensure instance_type is a valid non-empty string
        if not instance_type:
            instance_type = "unknown"

        # Location
        location = getattr(vm, "location", None)

        # Zones
        zones = getattr(vm, "zones", None)
        availability_zone = zones[0] if zones else None

        # Launch time approximation
        launch_time = None
        if instance_view and hasattr(instance_view, "statuses"):
            for s in instance_view.statuses:
                t = getattr(s, "time", None)
                if t is not None:
                    launch_time = str(t)
                    break

        return {
            # Use VMSS instance_id as canonical machine id (Azure delete_instances expects this shape).
            "instance_id": str(instance_id),
            "status": status,
            "private_ip": private_ip,
            "public_ip": public_ip,
            "launch_time": launch_time,
            "instance_type": instance_type,
            "subnet_id": subnet_id,
            "vpc_id": None,  # Azure uses VNet, stored in network_config
            "availability_zone": availability_zone,
            "provider_type": "azure",
            "provider_data": {
                "vmss_name": vmss_name,
                "resource_group": resource_group,
                "vmss_instance_id": instance_id,
                "vm_id": vm_id,
                "location": location,
                "fleet_errors": fleet_errors,
            },
        }

    def _extract_vm_errors(
        self,
        statuses: list[Any],
        *,
        instance_id: str,
        vmss_name: str,
    ) -> list[dict[str, Any]]:
        """Extract provisioning failures from Azure instance view statuses."""
        errors: list[dict[str, Any]] = []

        for status in statuses:
            code = str(_status_attr(status, "code", "") or "")
            level = str(_status_attr(status, "level", "") or "")
            message = _status_attr(status, "message")
            display_status = _status_attr(status, "display_status")

            is_failure = code.lower().startswith("provisioningstate/failed") or level.lower() == "error"
            if not is_failure:
                continue

            errors.append({
                "error_code": "ProvisioningStateFailed",
                "error_message": str(message or display_status or code or "Azure provisioning failed"),
                "instance_id": instance_id,
                "resource_id": vmss_name,
                "status_code": code,
                "status_level": level or None,
            })

        return errors

    # ------------------------------------------------------------------
    # Example templates
    # ------------------------------------------------------------------

    @classmethod
    def get_example_templates(cls) -> list[dict[str, Any]]:
        return [
            {
                "template_id": "azure-vmss-linux-basic",
                "name": "Azure VMSS Linux Basic",
                "description": "VMSS with Ubuntu 22.04 LTS on Standard_D4s_v5",
                "provider_type": "azure",
                "provider_api": AzureProviderApi.VMSS.value,
                "vm_size": "Standard_D4s_v5",
                "resource_group": "my-resource-group",
                "location": "eastus2",
                "image": {
                    "publisher": "Canonical",
                    "offer": "0001-com-ubuntu-server-jammy",
                    "sku": "22_04-lts-gen2",
                    "version": "latest",
                },
                "max_instances": 2,
            },
            {
                "template_id": "azure-vmss-spot",
                "name": "Azure VMSS Spot Instances",
                "description": "VMSS with Spot VMs for cost-effective workloads",
                "provider_type": "azure",
                "provider_api": AzureProviderApi.VMSS.value,
                "vm_size": "Standard_D4s_v5",
                "resource_group": "my-resource-group",
                "location": "eastus2",
                "priority": "Spot",
                "eviction_policy": "Deallocate",
                "billing_profile_max_price": -1.0,
                "image": {
                    "publisher": "Canonical",
                    "offer": "0001-com-ubuntu-server-jammy",
                    "sku": "22_04-lts-gen2",
                    "version": "latest",
                },
                "max_instances": 5,
            },
        ]
