"""Dependency Injection package."""

from .container import DIContainer, get_container, reset_container
from .contracts import (
    CompositeDIPort,
    CQRSHandlerRegistrationPort,
    DependencyRegistration,
    DIConfigurationPort,
    DIContainerPort,
    DIEventPort,
    DILifecycle,
    DIScope,
    DIServiceLocatorPort,
)
from .exceptions import (
    CircularDependencyError,
    DependencyRegistrationError,
    DependencyResolutionError,
    DIConfigurationError,
    FactoryError,
    InstantiationError,
    UnregisteredDependencyError,
    UntypedParameterError,
)
from .injectable import (
    InjectableMetadata,
    OptionalDependency,
    command_handler,
    event_handler,
    factory,
    get_dependencies,
    get_handler_type,
    get_injectable_info,
    get_injectable_metadata,
    injectable,
    is_cqrs_handler,
    is_injectable,
    is_singleton,
    lazy,
    optional_dependency,
    query_handler,
    requires,
    singleton,
)

__all__: list[str] = [
    # Container
    "DIContainer",
    "get_container",
    "reset_container",
    # Contracts
    "CQRSHandlerRegistrationPort",
    "CompositeDIPort",
    "DIConfigurationPort",
    "DIContainerPort",
    "DIEventPort",
    "DILifecycle",
    "DIScope",
    "DIServiceLocatorPort",
    "DependencyRegistration",
    # Exceptions
    "CircularDependencyError",
    "DIConfigurationError",
    "DependencyRegistrationError",
    "DependencyResolutionError",
    "FactoryError",
    "InstantiationError",
    "UnregisteredDependencyError",
    "UntypedParameterError",
    # Injectable decorators / utilities
    "InjectableMetadata",
    "OptionalDependency",
    "command_handler",
    "event_handler",
    "factory",
    "get_dependencies",
    "get_handler_type",
    "get_injectable_info",
    "get_injectable_metadata",
    "injectable",
    "is_cqrs_handler",
    "is_injectable",
    "is_singleton",
    "lazy",
    "optional_dependency",
    "query_handler",
    "requires",
    "singleton",
]
