"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Generic, TypeVar

"""Command and Query interfaces for CQRS pattern."""
T = TypeVar("T")
R = TypeVar("R")
__all__: list[str] = ...

class Query(ABC):
    """Base interface for queries."""

    ...

class QueryHandler(Generic[T, R], ABC):
    """Base interface for query handlers."""
    @abstractmethod
    async def handle(self, query: T) -> R:
        """
        Handle a query asynchronously.

        Args:
            query: Query to handle (strongly typed)

        Returns:
            Query result (strongly typed)

        Raises:
            ValidationError: If query is invalid
        """
        ...

class Command(ABC):
    """Base interface for commands."""

    ...
