"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Any, Optional, TYPE_CHECKING, Union
from pydantic import BaseModel

"""Base DTO class with stable API and clean snake_case format."""
if TYPE_CHECKING:
    ...
class BaseDTO(BaseModel):
    """
    Base class for all DTOs with stable API and clean snake_case format.

    This class provides a future-proof abstraction layer that:
    - Uses pure snake_case internally (Pythonic)
    - Provides stable to_dict()/from_dict() API
    - Abstracts away Pydantic implementation details
    - Allows easy framework switching if needed

    External format conversion (camelCase) is handled at scheduler strategy level.
    """
    model_config = ...
    def to_dict(self) -> dict[str, Any]:
        """
        Stable public API - returns clean snake_case dictionary.

        This method provides a stable interface that abstracts away the underlying
        serialization framework. External format conversion (camelCase) should be
        handled at the scheduler strategy level, not here.

        Returns:
            Dict with snake_case keys (Pythonic format)
        """
        ...
    
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> BaseDTO:
        """
        Stable public API - creates instance from snake_case dictionary.

        This method provides a stable interface that abstracts away the underlying
        serialization framework.

        Args:
            data: Dictionary with snake_case keys

        Returns:
            New instance of the DTO
        """
        ...
    
    @staticmethod
    def serialize_enum(value: Union[Enum, str, None]) -> Optional[str]:
        """
        Serialize enum to string value.

        Args:
            value: Enum, string, or None value

        Returns:
            String representation or None
        """
        ...
    


class BaseCommand(BaseDTO):
    """Base class for command DTOs."""
    command_id: Optional[str] = ...
    correlation_id: Optional[str] = ...
    metadata: dict[str, Any] = ...
    dry_run: bool = ...


class BaseQuery(BaseDTO):
    """Base class for query DTOs."""
    query_id: Optional[str] = ...
    correlation_id: Optional[str] = ...
    filters: dict[str, Any] = ...
    pagination: Optional[dict[str, Any]] = ...


class BaseResponse(BaseDTO):
    """Base class for response DTOs."""
    success: bool = ...
    message: Optional[str] = ...
    error_code: Optional[str] = ...
    metadata: dict[str, Any] = ...


class PaginatedResponse(BaseResponse):
    """Base class for paginated responses."""
    total_count: int = ...
    page: int = ...
    page_size: int = ...
    has_next: bool = ...
    has_previous: bool = ...


