"""Azure exceptions package."""

from orb.providers.azure.exceptions.azure_exceptions import (
    AuthenticationError,
    AuthorizationError,
    AzureConfigurationError,
    AzureEntityNotFoundError,
    AzureError,
    AzureInfrastructureError,
    AzureValidationError,
    ImageValidationError,
    LaunchError,
    NetworkError,
    QuotaExceededError,
    RateLimitError,
    ResourceCleanupError,
    ResourceInUseError,
    ResourceStateError,
    SubnetValidationError,
    TaggingError,
    TerminationError,
    VMNotFoundError,
    VMSizeValidationError,
    VMSSCreationError,
    VMSSNotFoundError,
)

__all__: list[str] = [
    "AuthenticationError",
    "AuthorizationError",
    "AzureConfigurationError",
    "AzureEntityNotFoundError",
    "AzureError",
    "AzureInfrastructureError",
    "AzureValidationError",
    "ImageValidationError",
    "LaunchError",
    "NetworkError",
    "QuotaExceededError",
    "RateLimitError",
    "ResourceCleanupError",
    "ResourceInUseError",
    "ResourceStateError",
    "SubnetValidationError",
    "TaggingError",
    "TerminationError",
    "VMNotFoundError",
    "VMSizeValidationError",
    "VMSSCreationError",
    "VMSSNotFoundError",
]

