"""Default scheduler strategy using native domain fields - no conversion needed."""

import os
from pathlib import Path
from typing import Any

from domain.base.ports.logging_port import LoggingPort
from domain.machine.aggregate import Machine
from domain.template.template_aggregate import Template
from infrastructure.scheduler.base.strategy import BaseSchedulerStrategy
from infrastructure.scheduler.default.field_mapper import DefaultFieldMapper


class DefaultSchedulerStrategy(BaseSchedulerStrategy):
    """
    Default scheduler strategy using native domain fields.

    This strategy uses templates and data in their native domain format
    without any field mapping or conversion. It serves as:
    - Reference implementation for scheduler strategies
    - Testing baseline with pure domain objects
    - Simple integration for systems using domain format directly
    """

    def __init__(self) -> None:
        """Initialize the instance."""
        self._config_manager = None
        self._logger = None
        # Initialize field mapper
        self.field_mapper = DefaultFieldMapper()

    @property
    def config_manager(self) -> Any:
        if self._config_manager is None:
            from domain.base.ports.configuration_port import ConfigurationPort
            from infrastructure.di.container import get_container, is_container_ready

            if is_container_ready():
                self._config_manager = get_container().get(ConfigurationPort)
        return self._config_manager

    @property
    def logger(self) -> Any:
        if self._logger is None:
            from infrastructure.di.container import get_container, is_container_ready

            if is_container_ready():
                self._logger = get_container().get(LoggingPort)
            else:
                from infrastructure.logging.logger import get_logger

                return get_logger(__name__)  # fallback, don't cache — pick up DI logger once ready
        return self._logger

    def get_scheduler_type(self) -> str:
        """Return the scheduler type identifier."""
        return "default"

    def get_scripts_directory(self) -> Path | None:
        """Default strategy has no scripts directory."""
        return None

    def _templates_filename_pattern_key(self) -> str:
        return "provider_type"

    def _templates_filename_fallback(self, provider_name: str, provider_type: str) -> str:
        return f"{provider_type}_templates.json"

    def load_templates_from_path(
        self, template_path: str, provider_override: Any = None
    ) -> list[dict[str, Any]]:
        """Load templates from a specific path.

        If the file was generated by a different scheduler (detected via scheduler_type
        metadata), delegates to that scheduler's load_templates_from_path so field
        mapping and transformations are applied correctly.
        """
        if not os.path.exists(template_path):
            self.logger.debug("Template file not found: %s", template_path)
            return []

        try:
            # Peek at the file to detect scheduler_type metadata
            import json

            with open(template_path) as f:
                data = json.load(f)

            file_scheduler_type = data.get("scheduler_type") if isinstance(data, dict) else None

            # Files without scheduler_type were generated by hostfactory (legacy default)
            if not file_scheduler_type:
                file_scheduler_type = "hostfactory"

            if file_scheduler_type != "default":
                self.logger.debug(
                    "Templates file was generated by '%s' scheduler, delegating load",
                    file_scheduler_type,
                )
                delegate = self._get_strategy_for_type(file_scheduler_type)
                if delegate:
                    return delegate.load_templates_from_path(template_path, provider_override)

            templates = self._load_single_file_from_data(data)
            self.logger.debug("Loaded %d templates from %s", len(templates), template_path)
            return templates
        except Exception as e:
            self.logger.error("Error loading templates from %s: %s", template_path, e)
            return []

    def _get_strategy_for_type(self, scheduler_type: str):
        """Return a strategy instance for the given scheduler type, or None if unknown."""
        if scheduler_type in ("hostfactory", "hf"):
            from infrastructure.scheduler.hostfactory.hostfactory_strategy import (
                HostFactorySchedulerStrategy,
            )

            return HostFactorySchedulerStrategy()
        return None

    def _load_single_file_from_data(self, data: Any) -> list[dict[str, Any]]:
        """Extract templates list from already-parsed JSON data."""
        if isinstance(data, dict) and "templates" in data:
            return data["templates"]
        elif isinstance(data, list):
            return data
        return []

    def _load_single_file(self, template_path: str) -> list[dict[str, Any]]:
        """Load templates from a single file."""
        try:
            import json

            with open(template_path) as f:
                data = json.load(f)
            return self._load_single_file_from_data(data)
        except Exception:
            return []

    def _get_provider_name(self) -> str:
        """Get the active provider instance name via proper DI."""
        try:
            from application.services.provider_registry_service import ProviderRegistryService
            from infrastructure.di.container import get_container

            container = get_container()
            provider_service = container.get(ProviderRegistryService)
            selection_result = provider_service.select_active_provider()
            return selection_result.provider_name
        except Exception as e:
            self.logger.warning("Failed to get provider instance name: %s", e)
            return "default"

    def _get_active_provider_type(self) -> str:
        """Get the active provider type via proper DI."""
        try:
            from application.services.provider_registry_service import ProviderRegistryService
            from infrastructure.di.container import get_container

            container = get_container()
            provider_service = container.get(ProviderRegistryService)
            selection_result = provider_service.select_active_provider()
            provider_type = selection_result.provider_type
            self.logger.debug("Active provider type: %s", provider_type)
            return provider_type
        except Exception as e:
            self.logger.warning("Failed to get active provider type, defaulting to 'aws': %s", e)
            return "aws"

    def get_config_file_path(self) -> str:
        """Get config file path - using default configuration."""
        # Use default_config.json
        return self.config_manager.resolve_file("config", "default_config.json")

    def parse_template_config(self, raw_data: dict[str, Any]) -> Template:
        """
        Parse template using native domain fields - no conversion needed.

        Since the template data is already in domain format, we can create
        the Template object directly without any field mapping.
        """
        try:
            # Direct domain object creation - templates are in native format
            return Template(**raw_data)
        except Exception as e:
            # Provide helpful error message for debugging
            raise ValueError(f"Failed to create Template from data: {e}. Data: {raw_data}")

    def parse_request_data(self, raw_data: dict[str, Any]) -> dict[str, Any]:
        """
        Parse request data using native domain format - no conversion needed.

        Request data is expected to be in domain format already.
        """

        # Request Status
        if "requests" in raw_data:
            return {
                "requests": [{"request_id": req.get("request_id")} for req in raw_data["requests"]]
            }

        # Request Machines - handle nested format (both snake_case and HF camelCase):
        # {"template": {"template_id": ..., "machine_count": ...}}
        # {"template": {"templateId": ..., "machineCount": ...}}
        if "template" in raw_data:
            template_data = raw_data["template"]
            return {
                "template_id": template_data.get("template_id") or template_data.get("templateId"),
                "requested_count": template_data.get("machine_count")
                or template_data.get("machineCount", 1),
                "request_type": template_data.get("request_type")
                or template_data.get("requestType", "provision"),
                "metadata": raw_data.get("metadata", {}),
            }

        # Request Machines - flat format
        # Return as-is since it's already in domain format
        return {
            "template_id": raw_data.get("template_id"),
            "requested_count": raw_data.get("requested_count", raw_data.get("count", 1)),
            "request_type": raw_data.get("request_type", "provision"),
            "request_id": raw_data.get("request_id"),
            "metadata": raw_data.get("metadata", {}),
        }

    def format_templates_response(self, templates: list[Any], include_detailed_fields: bool = False) -> dict[str, Any]:
        """
        Format domain Templates to native domain response format.

        Uses the new architecture-compliant method for consistency.
        """
        return {
            "templates": [self.format_template_for_display(template, include_detailed_fields) for template in templates],
            "message": "Templates retrieved successfully",
            "total_count": len(templates),
        }

    def format_template_for_display(self, template: Any, include_detailed_fields: bool = False) -> dict[str, Any]:
        """Format template for display, adding required schema fields."""
        d = template.to_dict()
        # Schema requires max_capacity (alias for max_instances)
        if "max_capacity" not in d:
            d["max_capacity"] = d.get("max_instances", 1)
        # Schema requires instance_type - derive from machine_types if available
        if "instance_type" not in d:
            machine_types = d.get("machine_types", {})
            d["instance_type"] = next(iter(machine_types), "") if machine_types else ""
        # Apply field filtering here (presentation concern belongs in strategy, not interface layer)
        if not include_detailed_fields:
            core_fields = {"template_id", "name", "description", "provider_api", "max_instances",
                           "max_capacity", "instance_type"}
            d = {k: v for k, v in d.items() if k in core_fields}
        return d

    def format_templates_for_generation(self, templates: list[dict]) -> list[dict]:
        """No conversion needed - use field mapper (identity mapping)."""
        return self.field_mapper.format_for_generation(templates)

    def format_machine_status_response(self, machines: list[Machine]) -> dict[str, Any]:
        """
        Format domain Machines to native domain response format.

        Uses the Machine's model_dump() method to serialize to native format.
        """
        return {
            "machines": [machine.model_dump() for machine in machines],
            "message": "Machine status retrieved successfully",
            "count": len(machines),
        }

    def format_machine_details_response(self, machine_data: dict) -> dict:
        """Format machine details with default fields."""
        return {
            "id": machine_data.get("id"),
            "name": machine_data.get("name"),
            "status": machine_data.get("status"),
            "provider": "default",
            "instance_type": machine_data.get("instance_type"),
            "region": machine_data.get("region"),
            "image_id": machine_data.get("image_id"),
            "private_ip": machine_data.get("private_ip"),
            "public_ip": machine_data.get("public_ip"),
            "subnet_id": machine_data.get("subnet_id"),
            "security_group_ids": machine_data.get("security_group_ids"),
            "status_reason": machine_data.get("status_reason"),
            "launch_time": machine_data.get("launch_time"),
            "termination_time": machine_data.get("termination_time"),
            "tags": machine_data.get("tags"),
        }

    def get_storage_base_path(self) -> str:
        """Get storage base path within working directory."""
        import os

        workdir = self.get_working_directory()
        return os.path.join(workdir, "data")

    def should_log_to_console(self) -> bool:
        """Check if logs should be written to console for Default scheduler.

        Default scheduler is interactive, always log to console.
        """
        return True

    def format_error_response(self, error: Exception, context: dict[str, Any]) -> dict[str, Any]:
        """Format error response for Default scheduler (console + JSON)."""
        import traceback

        # Log error
        self.logger.error("Scheduler error: %s", error)
        if context.get("verbose"):
            traceback.print_exc()

        # Return JSON
        response = {"success": False, "error": str(error)}

        if context.get("verbose"):
            response["traceback"] = traceback.format_exc()

        return response

    def get_exit_code_for_status(self, status: str) -> int:
        """Default scheduler exit codes: 1 for any problem, 0 for success."""
        problem_statuses = ["failed", "cancelled", "timeout", "partial"]
        return 1 if status in problem_statuses else 0

    def format_health_response(self, checks: list[dict[str, Any]]) -> dict[str, Any]:
        """Format health check response for Default scheduler."""
        passed = sum(1 for c in checks if c.get("status") == "pass")
        failed = len(checks) - passed

        return {
            "success": failed == 0,
            "checks": checks,
            "summary": {"total": len(checks), "passed": passed, "failed": failed},
        }

    def get_directory(self, file_type: str) -> str | None:
        """Get directory path for the given file type."""
        import os

        workdir = self.get_working_directory()

        if file_type in ["conf", "template", "legacy"]:
            return os.path.join(workdir, "config")
        elif file_type == "log":
            return os.path.join(workdir, "logs")
        elif file_type in ["work", "data"]:
            return workdir
        else:
            return workdir

    def format_request_response(self, request_data: dict[str, Any]) -> dict[str, Any]:
        """Format request creation response to native domain format."""
        # If this is a status/detail response, pass through the requests list and status
        if "requests" in request_data:
            return {
                "requests": request_data.get("requests", []),
                "status": request_data.get("status", "complete"),
                "message": request_data.get("message", "Status retrieved successfully"),
                "errors": request_data.get("errors"),
            }

        # Get status and error info
        status = request_data.get("status", "pending")
        error_message = request_data.get("error_message")
        request_id = request_data.get("request_id", request_data.get("requestId"))

        # Status-based message and response logic
        if status == "failed":
            return {
                "error": f"Request failed: {error_message or 'Unknown error'}",
                "request_id": request_id,
            }
        elif status == "cancelled":
            return {"error": "Request cancelled", "request_id": request_id}
        elif status == "timeout":
            return {"error": "Request timed out", "request_id": request_id}
        elif status == "partial":
            return {
                "warning": f"Request partially completed: {error_message or 'Some resources failed'}",
                "request_id": request_id,
            }
        elif status == "complete":
            return {"request_id": request_id, "message": "Request completed successfully"}
        elif status == "in_progress":
            return {"request_id": request_id, "message": "Request in progress"}
        elif status == "pending":
            return {"request_id": request_id, "message": "Request submitted successfully"}
        else:
            return {
                "request_id": request_id,
                "message": request_data.get("message", "Request status unknown"),
            }
