#!/bin/bash
set -e

# Create changelog update PR for releases
# Usage: ./create_changelog_pr.sh TAG_NAME

if [ $# -ne 1 ]; then
    echo "Usage: $0 TAG_NAME"
    echo "Example: $0 v1.2.3"
    exit 1
fi

TAG_NAME="$1"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_debug() {
    echo -e "${BLUE}[DEBUG]${NC} $1"
}

create_changelog_pr() {
    local tag_name=$1
    local branch_name="changelog/release-${tag_name}"
    
    log_info "Creating changelog PR for release $tag_name"
    
    # Ensure we're on main and up to date
    git checkout main
    git pull origin main
    
    # Create and checkout new branch
    log_debug "Creating branch: $branch_name"
    git checkout -b "$branch_name"
    
    # Update changelog
    log_info "Updating changelog..."
    make changelog-update VERSION="$tag_name"
    
    # Check if there are changes to commit
    if git diff --quiet CHANGELOG.md .project.yml; then
        log_info "No changelog changes needed"
        git checkout main
        git branch -D "$branch_name" 2>/dev/null || true
        return 0
    fi
    
    # Commit changes
    log_debug "Committing changelog updates"
    git add CHANGELOG.md .project.yml
    git commit -m "docs: update changelog for release $tag_name

- Updated CHANGELOG.md with release notes
- Version bump in .project.yml

Auto-generated by release process."
    
    # Push branch
    log_debug "Pushing branch to origin"
    git push origin "$branch_name"
    
    # Create PR
    log_info "Creating pull request"
    gh pr create \
        --title "Update changelog for release $tag_name" \
        --body "Auto-generated changelog update for release $tag_name

This PR updates the CHANGELOG.md with release notes and bumps the version in .project.yml.

**Release:** $tag_name
**Type:** Automated changelog update

### Changes
- Updated CHANGELOG.md with release notes
- Bumped version in .project.yml

### Checklist
- [x] Changelog entries are accurate
- [x] Version bump is correct
- [x] Auto-generated by release process" \
        --label "changelog,automated" \
        --base main \
        --head "$branch_name"
    
    # Return to main branch
    git checkout main
    
    log_info "Changelog PR created successfully"
    echo "Branch: $branch_name"
    echo "PR: $(gh pr view --json url --jq '.url' "$branch_name")"
}

# Execute the function
create_changelog_pr "$TAG_NAME"
