name: Container Image Cleanup

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  cleanup:
    name: Delete Untagged Container Images
    runs-on: ubuntu-latest

    steps:
    - name: Delete untagged container images
      uses: actions/delete-package-versions@v5
      with:
        package-name: open-resource-broker
        package-type: container
        min-versions-to-keep: 0
        delete-only-untagged-versions: true
