"""initial sql schema

Revision ID: f6d2ba73f23c
Revises:
Create Date: 2026-06-24 09:57:56.719094

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6d2ba73f23c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "machines",
        sa.Column("machine_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("instance_type", sa.String(length=50), nullable=False),
        sa.Column("image_id", sa.String(length=255), nullable=False),
        sa.Column("template_id", sa.String(length=255), nullable=False),
        sa.Column("provider_api", sa.String(length=255), nullable=False),
        sa.Column("provider_name", sa.String(length=255), nullable=False),
        sa.Column("private_ip", sa.String(length=45), nullable=True),
        sa.Column("public_ip", sa.String(length=45), nullable=True),
        sa.Column("private_dns_name", sa.Text(), nullable=True),
        sa.Column("public_dns_name", sa.Text(), nullable=True),
        sa.Column("launch_time", sa.BIGINT(), nullable=True),
        sa.Column("termination_time", sa.Text(), nullable=True),
        sa.Column("provisioning_started_at", sa.Text(), nullable=True),
        sa.Column("uptime_seconds", sa.Integer(), nullable=True),
        sa.Column("provider_type", sa.String(length=255), nullable=True),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("cloud_host_id", sa.String(length=255), nullable=True),
        sa.Column("provider_data", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=255), nullable=True),
        sa.Column("return_request_id", sa.String(length=255), nullable=True),
        sa.Column("availability_zone", sa.String(length=50), nullable=True),
        sa.Column("region", sa.Text(), nullable=True),
        sa.Column("subnet_id", sa.String(length=255), nullable=True),
        sa.Column("vpc_id", sa.Text(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.Column("health_checks", sa.Text(), nullable=True),
        sa.Column("price_type", sa.String(length=50), nullable=True),
        sa.Column("result", sa.String(length=255), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("vcpus", sa.Integer(), nullable=True),
        sa.Column("security_group_ids", sa.Text(), nullable=True),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("schema_version", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("machine_id"),
    )
    op.create_table(
        "requests",
        sa.Column("request_id", sa.String(length=255), nullable=False),
        sa.Column("template_id", sa.String(length=255), nullable=False),
        sa.Column("request_type", sa.String(length=50), nullable=False),
        sa.Column("provider_type", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("requested_count", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("desired_capacity", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("successful_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("failed_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.Text(), nullable=True),
        sa.Column("started_at", sa.Text(), nullable=True),
        sa.Column("first_status_check", sa.Text(), nullable=True),
        sa.Column("last_status_check", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.Text(), nullable=True),
        sa.Column("status_message", sa.Text(), nullable=True),
        sa.Column("error_details", sa.Text(), nullable=True),
        sa.Column("success_rate", sa.Text(), nullable=True),
        sa.Column("provider_api", sa.String(length=255), nullable=True),
        sa.Column("provider_name", sa.String(length=255), nullable=True),
        sa.Column("provider_data", sa.Text(), nullable=True),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("resource_ids", sa.Text(), nullable=True),
        sa.Column("machine_ids", sa.Text(), nullable=True),
        sa.Column("launch_template_id", sa.String(length=255), nullable=True),
        sa.Column("launch_template_version", sa.String(length=50), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("schema_version", sa.String(length=50), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.Column("machine_count", sa.Integer(), nullable=True),
        sa.Column("timeout", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("request_id"),
    )
    op.create_table(
        "templates",
        sa.Column("template_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("1")),
        sa.Column("provider_api", sa.String(length=255), nullable=True),
        sa.Column("provider_name", sa.String(length=255), nullable=True),
        sa.Column("provider_type", sa.String(length=255), nullable=True),
        sa.Column("provider_data", sa.Text(), nullable=True),
        sa.Column("image_id", sa.String(length=255), nullable=True),
        sa.Column("max_instances", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("instance_type", sa.String(length=50), nullable=True),
        sa.Column("machine_types", sa.Text(), nullable=True),
        sa.Column("machine_types_ondemand", sa.Text(), nullable=True),
        sa.Column("machine_types_priority", sa.Text(), nullable=True),
        sa.Column("subnet_ids", sa.Text(), nullable=True),
        sa.Column("security_group_ids", sa.Text(), nullable=True),
        sa.Column("network_zones", sa.Text(), nullable=True),
        sa.Column("public_ip_assignment", sa.Text(), nullable=True),
        sa.Column("price_type", sa.String(length=50), nullable=True),
        sa.Column("allocation_strategy", sa.String(length=50), nullable=True),
        sa.Column("max_price", sa.Text(), nullable=True),
        sa.Column("root_device_volume_size", sa.Integer(), nullable=True),
        sa.Column("volume_type", sa.String(length=50), nullable=True),
        sa.Column("iops", sa.Integer(), nullable=True),
        sa.Column("throughput", sa.Integer(), nullable=True),
        sa.Column("storage_encryption", sa.Boolean(), nullable=True),
        sa.Column("encryption_key", sa.Text(), nullable=True),
        sa.Column("key_name", sa.String(length=255), nullable=True),
        sa.Column("user_data", sa.Text(), nullable=True),
        sa.Column("instance_profile", sa.Text(), nullable=True),
        sa.Column("launch_template_id", sa.String(length=255), nullable=True),
        sa.Column("monitoring_enabled", sa.Boolean(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("schema_version", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("template_id"),
    )
    # ### end Alembic commands ###

    op.create_index("ix_machines_status", "machines", ["status"])
    op.create_index("ix_machines_provider_api", "machines", ["provider_api"])


def downgrade() -> None:
    """Downgrade schema."""
    raise NotImplementedError(
        "Initial migration: downgrade would drop all tables and destroy data. "
        "Restore from backup instead."
    )
